/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/hRW2PUezr9U
 */

import { JSX, SVGProps } from "react";

export function BenefitsObjectionsData() {
  return (
    <section className="benefits w-full py-12 md:py-24 lg:py-32 xl:py-40">
      <div className="container grid items-center justify-center gap-4 px-4 text-center md:px-6 lg:gap-10">
        <div className="space-y-3">
          <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
            Experience the Difference
          </h2>
          <p className="mx-auto max-w-[700px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
            Transform your bathroom with a custom Italian shower. Discover the
            benefits and why you should choose us.
          </p>
        </div>
        <div className="grid max-w-sm w-full grid-cols-2 gap-4 mx-auto md:grid-cols-3 md:max-w-none md:gap-6 lg:grid-cols-3 xl:grid-cols-3">
          <div className="flex flex-col items-center justify-center space-y-2 border border-gray-200  rounded-xl p-4 hover:shadow-lg transition-transform scale-105 translate-y-1  dark:hover:shadow-lg dark:border-gray-800">
            <DropletsIcon className="w-8 h-8" />
            <h3 className="text-sm font-bold tracking-wide">Waterproof</h3>
            <p className="text-xs text-gray-500">Keeps your bathroom dry</p>
          </div>
          <div className="flex flex-col items-center justify-center space-y-2 border border-gray-200  rounded-xl p-4 hover:shadow-lg transition-transform scale-105 translate-y-1  dark:hover:shadow-lg dark:border-gray-800">
            <ShowerHeadIcon className="w-8 h-8" />
            <h3 className="text-sm font-bold tracking-wide">Elegant</h3>
            <p className="text-xs text-gray-500">Adds style to your bathroom</p>
          </div>
          <div className="flex flex-col items-center justify-center space-y-2 border border-gray-200  rounded-xl p-4 hover:shadow-lg transition-transform scale-105 translate-y-1 dark:hover:shadow-lg dark:border-gray-800">
            <ThermometerIcon className="w-8 h-8" />
            <h3 className="text-sm font-bold tracking-wide">Thermostatic</h3>
            <p className="text-xs text-gray-500">
              Consistent water temperature
            </p>
          </div>
          <div className="flex flex-col items-center justify-center space-y-2 border border-gray-200  rounded-xl p-4 hover:shadow-lg transition-transform scale-105 translate-y-1 dark:hover:shadow-lg dark:border-gray-800">
            <ActivityIcon className="w-8 h-8" />
            <h3 className="text-sm font-bold tracking-wide">Easy to Clean</h3>
            <p className="text-xs text-gray-500">Saves time and effort</p>
          </div>
          <div className="flex flex-col items-center justify-center space-y-2 border border-gray-200  rounded-xl p-4 hover:shadow-lg transition-transform scale-105 translate-y-1 dark:hover:shadow-lg dark:border-gray-800">
            <ActivityIcon className="w-8 h-8" />
            <h3 className="text-sm font-bold tracking-wide">Spa-like</h3>
            <p className="text-xs text-gray-500">Relaxing shower experience</p>
          </div>
        </div>
        <div className="mx-auto max-w-[700px] grid gap-4 md:gap-6 lg:gap-10">
          <div className="grid gap-2">
            <h3 className="text-xl font-bold">
              Objection: Will the Italian shower installation process be
              disruptive?
            </h3>
            <p className="text-sm text-gray-500">
              We understand the importance of minimizing disruption during the
              installation process. Our team is highly skilled and experienced,
              ensuring that the installation is carried out efficiently and
              professionally. We will take the necessary measures to protect
              your home and keep the work area clean. Once the installation is
              complete, you'll be able to enjoy your new Italian shower without
              any hassle.
            </p>
          </div>
          <div className="grid gap-2">
            <h3 className="text-xl font-bold">
              Objection: Is an Italian shower difficult to maintain?
            </h3>
            <p className="text-sm text-gray-500">
              While Italian showers are known for their sleek and modern
              appearance, some customers may have concerns about the maintenance
              involved. However, we offer guidance on the best cleaning
              practices to keep your Italian shower looking pristine. With
              regular care and the right cleaning products, maintaining your
              Italian shower can be straightforward. We'll provide you with the
              information you need to ensure that your shower remains in top
              condition.
            </p>
          </div>
          <div className="grid gap-2">
            <h3 className="text-xl font-bold">
              Objection: Will an Italian shower make my bathroom feel cold?
            </h3>
            <p className="text-sm text-gray-500">
              Italian showers are designed to create a sense of openness and
              spaciousness in the bathroom. While some customers may have
              concerns about the potential for drafts or a chilly atmosphere, we
              can address these issues by offering solutions such as underfloor
              heating or the installation of a glass enclosure. These options
              can help to maintain a comfortable temperature in the shower area
              while preserving the aesthetic appeal of the Italian shower. We
              can discuss the available features and customization options to
              ensure that your Italian shower meets your preferences.
            </p>
          </div>
        </div>
      </div>
    </section>
  );
}

function DropletsIcon(
  props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>
) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M7 16.3c2.2 0 4-1.83 4-4.05 0-1.16-.57-2.26-1.71-3.19S7.29 6.75 7 5.3c-.29 1.45-1.14 2.84-2.29 3.76S3 11.1 3 12.25c0 2.22 1.8 4.05 4 4.05z" />
      <path d="M12.56 6.6A10.97 10.97 0 0 0 14 3.02c.5 2.5 2 4.9 4 6.5s3 3.5 3 5.5a6.98 6.98 0 0 1-11.91 4.97" />
    </svg>
  );
}

function ShowerHeadIcon(
  props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>
) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m4 4 2.5 2.5" />
      <path d="M13.5 6.5a4.95 4.95 0 0 0-7 7" />
      <path d="M15 5 5 15" />
      <path d="M14 17v.01" />
      <path d="M10 16v.01" />
      <path d="M13 13v.01" />
      <path d="M16 10v.01" />
      <path d="M11 20v.01" />
      <path d="M17 14v.01" />
      <path d="M20 11v.01" />
    </svg>
  );
}

function ThermometerIcon(
  props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>
) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M14 4v10.54a4 4 0 1 1-4 0V4a2 2 0 0 1 4 0Z" />
    </svg>
  );
}

function ActivityIcon(
  props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>
) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 12h-4l-3 9L9 3l-3 9H2" />
    </svg>
  );
}
